### PR TITLE
Guide on how to host golds dankgrinder on replit

### PR DESCRIPTION
**Pull request by sneazy-ibo**
- Create a team in replit and fork dankgrinder inside a project there (give it a random name and remove the description otherwise people would be able to get ur token by searching for _dankgrinder_ on replit)
- Add a `main.py` with the following code:
```python
from flask import Flask
from threading import Thread
import time
import os
from multiprocessing import Process

app = Flask('')

@app.route('/')
def home():
    return "<h1>Dankgrinder is online! u,u</h1>"

def printer():
  os.system('python3 grinder.py')

def run():
  app.run(host='0.0.0.0',port=8080)

if __name__ =="__main__":
    t = Process(target=run)
    t.start()
    t2 = Process(target=printer)
    t2.start()
```
- Add a `grinder.py` with the following code:
```python
import os
os.system('./dankgrinder')
```
- Press on `show hidden files` at the three dot menu and a `.replit` should pop up, replace the following text
```python
language = "py"
run = "python3 main.py"
```
- Go to the console and write `go build`
- Run the project and copy the url that pops up
- Go to uptimerobot.com and create a new monitor with your URL to host dg

- **Note:** Replit has a bug which causes dg to crash and run randomly, so the shifts are pretty fucked up. This can also be a good thing since it will make your token look more human bc it grinds at random times

### CODE REVIEW

**Comment by Antimony051** [comment]
> * people would be able to get ur token by searching for _dankgrinder_ on replit

you can use environment variable to hide your token!

**Comment by sneazy-ibo** [comment]
> > * people would be able to get ur token by searching for _dankgrinder_ on replit
> 
> you can use environment variable to hide your token!

Yeah but you need to modify the whole code for that

**Comment by SoulHunter287** [comment]
give credits when xD

**Comment by SoulHunter287** [comment]
also thats not a bug that it crashed dg they restart their servers randomly  caz of that all the repls stop for 1 second or something

**Comment by sneazy-ibo** [comment]
> also thats not a bug that it crashed dg they restart their servers randomly caz of that all the repls stop for 1 second or something

Ah I see that makes sense, well I found someone who was able to fix this on replit with an automatic restart after crashes, saving shifts locally and also using secrets for tokens and channelids, but it's sadly outdated and he won't update it anymore.

Also Van said smth like this abt replit:
_Hosting dankgrinder on services like repl.it might mess-up the shifts and repeat the first active shift over and over again. This is not an issue with dankgrinder but one with repl.it and allocation of it's resources._

**Pull request closed without merging**
